import { Pool } from "pg";

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: {
    rejectUnauthorized: false,
    checkServerIdentity: () => undefined,
  }
});

const createTables = async () => {
  const client = await pool.connect();
  try {
    // Drop table if it exists to ensure clean structure
    await client.query(`DROP TABLE IF EXISTS recipes`);

    await client.query(`
      CREATE TABLE recipes (
        id SERIAL PRIMARY KEY,
        title VARCHAR(255) NOT NULL,
        description TEXT,
        ingredients TEXT[] NOT NULL,
        instructions TEXT[] NOT NULL,
        cooking_time INTEGER NOT NULL,
        difficulty VARCHAR(50) NOT NULL,
        servings INTEGER DEFAULT 4,
        image_url VARCHAR(500),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      );
    `);
    console.log("Tables created successfully");
  } finally {
    client.release();
  }
};

const seedData = async () => {
  const client = await pool.connect();
  try {
    // Table is already clean since we dropped and recreated it

    const recipes = [
      {
        title: "Spaghetti Carbonara",
        description:
          "A classic Italian pasta dish with eggs, cheese, and pancetta",
        ingredients: [
          "400g spaghetti",
          "200g pancetta or guanciale",
          "4 large eggs",
          "100g Pecorino Romano cheese",
          "100g Parmigiano Reggiano",
          "Black pepper",
          "Salt",
        ],
        instructions: [
          "Bring a large pot of salted water to boil and cook spaghetti according to package directions",
          "While pasta cooks, cut pancetta into small cubes and cook in a large skillet until crispy",
          "In a bowl, whisk together eggs, grated cheeses, and black pepper",
          "Drain pasta, reserving 1 cup of pasta water",
          "Add hot pasta to the skillet with pancetta, remove from heat",
          "Quickly stir in egg mixture, adding pasta water as needed to create a creamy sauce",
          "Serve immediately with extra cheese and black pepper",
        ],
        cooking_time: 20,
        difficulty: "Medium",
        servings: 4,
        image_url:
          "https://images.unsplash.com/photo-1621996346565-e3dbc353d2e5?w=400",
      },
      {
        title: "Chicken Tikka Masala",
        description: "Creamy and flavorful Indian curry with tender chicken",
        ingredients: [
          "800g chicken breast, cubed",
          "2 tbsp tikka masala paste",
          "400ml coconut milk",
          "400g canned tomatoes",
          "1 onion, diced",
          "3 cloves garlic, minced",
          "1 inch ginger, grated",
          "2 tbsp vegetable oil",
          "Fresh cilantro",
          "Basmati rice",
        ],
        instructions: [
          "Marinate chicken in tikka masala paste for 30 minutes",
          "Heat oil in a large pan and cook chicken until browned, set aside",
          "In the same pan, sauté onion, garlic, and ginger until soft",
          "Add tomatoes and cook for 5 minutes",
          "Return chicken to pan, add coconut milk and simmer for 20 minutes",
          "Garnish with fresh cilantro and serve with basmati rice",
        ],
        cooking_time: 45,
        difficulty: "Medium",
        servings: 4,
        image_url:
          "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400",
      },
      {
        title: "Caesar Salad",
        description: "Fresh and crispy salad with homemade dressing",
        ingredients: [
          "2 heads romaine lettuce",
          "1/2 cup Parmesan cheese",
          "1 cup croutons",
          "2 anchovy fillets",
          "2 cloves garlic",
          "1 egg yolk",
          "2 tbsp lemon juice",
          "1/4 cup olive oil",
          "Black pepper",
        ],
        instructions: [
          "Wash and chop romaine lettuce into bite-sized pieces",
          "Make dressing by whisking together anchovy, garlic, egg yolk, and lemon juice",
          "Slowly drizzle in olive oil while whisking",
          "Toss lettuce with dressing, Parmesan, and croutons",
          "Season with black pepper and serve immediately",
        ],
        cooking_time: 15,
        difficulty: "Easy",
        servings: 4,
        image_url:
          "https://images.unsplash.com/photo-1546793665-c74683f339c1?w=400",
      },
      {
        title: "Chocolate Chip Cookies",
        description: "Classic homemade chocolate chip cookies",
        ingredients: [
          "2 1/4 cups all-purpose flour",
          "1 tsp baking soda",
          "1 tsp salt",
          "1 cup butter, softened",
          "3/4 cup granulated sugar",
          "3/4 cup brown sugar",
          "2 large eggs",
          "2 tsp vanilla extract",
          "2 cups chocolate chips",
        ],
        instructions: [
          "Preheat oven to 375°F (190°C)",
          "Mix flour, baking soda, and salt in a bowl",
          "Cream butter and sugars until light and fluffy",
          "Beat in eggs and vanilla",
          "Gradually mix in flour mixture",
          "Stir in chocolate chips",
          "Drop rounded tablespoons onto ungreased baking sheets",
          "Bake for 9-11 minutes until golden brown",
        ],
        cooking_time: 25,
        difficulty: "Easy",
        servings: 24,
        image_url:
          "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=400",
      },
      {
        title: "Beef Stir Fry",
        description: "Quick and healthy beef stir fry with vegetables",
        ingredients: [
          "500g beef sirloin, sliced",
          "2 cups mixed vegetables",
          "3 tbsp soy sauce",
          "2 tbsp oyster sauce",
          "1 tbsp cornstarch",
          "2 cloves garlic, minced",
          "1 inch ginger, grated",
          "2 tbsp vegetable oil",
          "Cooked rice",
        ],
        instructions: [
          "Slice beef thinly and marinate with soy sauce and cornstarch",
          "Heat oil in a wok or large pan over high heat",
          "Stir fry beef until browned, remove from pan",
          "Add vegetables, garlic, and ginger, stir fry for 2-3 minutes",
          "Return beef to pan, add oyster sauce",
          "Cook for 1-2 minutes until sauce thickens",
          "Serve hot over rice",
        ],
        cooking_time: 20,
        difficulty: "Easy",
        servings: 4,
        image_url:
          "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=400",
      },
      {
        title: "Margherita Pizza",
        description: "Classic Italian pizza with tomato, mozzarella, and basil",
        ingredients: [
          "1 pizza dough ball",
          "1/2 cup tomato sauce",
          "200g fresh mozzarella",
          "Fresh basil leaves",
          "2 tbsp olive oil",
          "Salt and pepper",
          "Cornmeal for dusting",
        ],
        instructions: [
          "Preheat oven to 500°F (260°C) with pizza stone if available",
          "Roll out pizza dough on a floured surface",
          "Spread tomato sauce evenly over dough",
          "Tear mozzarella into pieces and distribute over sauce",
          "Drizzle with olive oil and season with salt and pepper",
          "Bake for 12-15 minutes until crust is golden",
          "Top with fresh basil leaves before serving",
        ],
        cooking_time: 30,
        difficulty: "Medium",
        servings: 4,
        image_url:
          "https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?w=400",
      },
      {
        title: "Greek Yogurt Parfait",
        description: "Healthy breakfast parfait with berries and granola",
        ingredients: [
          "2 cups Greek yogurt",
          "1 cup mixed berries",
          "1/2 cup granola",
          "2 tbsp honey",
          "1/4 cup chopped nuts",
          "Fresh mint for garnish",
        ],
        instructions: [
          "Layer half the Greek yogurt in serving glasses",
          "Add a layer of mixed berries",
          "Sprinkle with granola and drizzle with honey",
          "Repeat layers with remaining ingredients",
          "Top with chopped nuts and fresh mint",
          "Serve immediately or refrigerate for up to 2 hours",
        ],
        cooking_time: 10,
        difficulty: "Easy",
        servings: 2,
        image_url:
          "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400",
      },
      {
        title: "Thai Green Curry",
        description: "Aromatic Thai curry with coconut milk and vegetables",
        ingredients: [
          "400ml coconut milk",
          "2 tbsp green curry paste",
          "400g mixed vegetables",
          "300g tofu or chicken",
          "2 tbsp fish sauce",
          "1 tbsp palm sugar",
          "Thai basil leaves",
          "Jasmine rice",
          "Lime wedges",
        ],
        instructions: [
          "Heat coconut milk in a large pot until it starts to separate",
          "Add green curry paste and stir until fragrant",
          "Add protein and cook until almost done",
          "Add vegetables and simmer for 5-7 minutes",
          "Season with fish sauce and palm sugar",
          "Garnish with Thai basil and serve with jasmine rice and lime",
        ],
        cooking_time: 35,
        difficulty: "Medium",
        servings: 4,
        image_url:
          "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400",
      },
      {
        title: "Avocado Toast",
        description: "Simple and nutritious avocado toast with toppings",
        ingredients: [
          "4 slices sourdough bread",
          "2 ripe avocados",
          "1 lemon",
          "Red pepper flakes",
          "Sea salt",
          "Black pepper",
          "Microgreens or sprouts",
          "Extra virgin olive oil",
        ],
        instructions: [
          "Toast bread until golden brown",
          "Mash avocados in a bowl with lemon juice, salt, and pepper",
          "Spread mashed avocado evenly on toast",
          "Drizzle with olive oil and sprinkle with red pepper flakes",
          "Top with microgreens and additional salt if needed",
          "Serve immediately while bread is still warm",
        ],
        cooking_time: 10,
        difficulty: "Easy",
        servings: 2,
        image_url:
          "https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=400",
      },
      {
        title: "Beef Tacos",
        description: "Authentic Mexican beef tacos with fresh toppings",
        ingredients: [
          "500g ground beef",
          "8 corn tortillas",
          "1 onion, diced",
          "2 cloves garlic, minced",
          "2 tbsp taco seasoning",
          "1 cup shredded lettuce",
          "1 cup diced tomatoes",
          "1/2 cup shredded cheese",
          "Sour cream",
          "Salsa",
          "Lime wedges",
        ],
        instructions: [
          "Brown ground beef in a large skillet over medium heat",
          "Add onion and garlic, cook until softened",
          "Stir in taco seasoning and cook for 2 minutes",
          "Warm tortillas in a dry skillet or microwave",
          "Fill tortillas with beef mixture",
          "Top with lettuce, tomatoes, cheese, sour cream, and salsa",
          "Serve with lime wedges on the side",
        ],
        cooking_time: 25,
        difficulty: "Easy",
        servings: 4,
        image_url:
          "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=400",
      },
      {
        title: "Chicken Noodle Soup",
        description: "Comforting homemade chicken noodle soup",
        ingredients: [
          "1 whole chicken",
          "2 carrots, sliced",
          "2 celery stalks, sliced",
          "1 onion, diced",
          "3 cloves garlic, minced",
          "200g egg noodles",
          "2 bay leaves",
          "Fresh parsley",
          "Salt and pepper",
          "Chicken broth",
        ],
        instructions: [
          "Place chicken in a large pot with water and bring to boil",
          "Reduce heat and simmer for 1 hour until chicken is cooked",
          "Remove chicken and shred meat, discard bones",
          "Add vegetables and garlic to broth, simmer for 20 minutes",
          "Add noodles and cook according to package directions",
          "Return shredded chicken to pot and heat through",
          "Season with salt and pepper, garnish with parsley",
        ],
        cooking_time: 90,
        difficulty: "Medium",
        servings: 6,
        image_url:
          "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400",
      },
      {
        title: "Chocolate Lava Cake",
        description: "Decadent chocolate lava cakes with molten center",
        ingredients: [
          "200g dark chocolate",
          "200g butter",
          "4 large eggs",
          "4 egg yolks",
          "1/2 cup sugar",
          "1/2 cup all-purpose flour",
          "Pinch of salt",
          "Butter for ramekins",
          "Cocoa powder for dusting",
        ],
        instructions: [
          "Preheat oven to 425°F (220°C) and butter 4 ramekins",
          "Melt chocolate and butter together until smooth",
          "Whisk eggs, egg yolks, and sugar until pale and thick",
          "Fold chocolate mixture into egg mixture",
          "Gently fold in flour and salt",
          "Divide batter among ramekins and bake for 12-14 minutes",
          "Let stand for 1 minute, then invert onto plates",
        ],
        cooking_time: 30,
        difficulty: "Hard",
        servings: 4,
        image_url:
          "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=400",
      },
      {
        title: "Quinoa Buddha Bowl",
        description:
          "Healthy vegetarian bowl with quinoa and roasted vegetables",
        ingredients: [
          "1 cup quinoa",
          "2 cups vegetable broth",
          "1 sweet potato, cubed",
          "1 cup chickpeas",
          "2 cups kale",
          "1 avocado",
          "1/4 cup tahini",
          "1 lemon",
          "Olive oil",
          "Salt and pepper",
        ],
        instructions: [
          "Cook quinoa in vegetable broth according to package directions",
          "Roast sweet potato and chickpeas with olive oil at 400°F for 25 minutes",
          "Massage kale with olive oil and lemon juice",
          "Make tahini dressing by mixing tahini, lemon juice, and water",
          "Assemble bowls with quinoa, roasted vegetables, and kale",
          "Top with sliced avocado and drizzle with tahini dressing",
        ],
        cooking_time: 40,
        difficulty: "Easy",
        servings: 2,
        image_url:
          "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400",
      },
      {
        title: "Shrimp Scampi",
        description: "Garlicky shrimp scampi with linguine pasta",
        ingredients: [
          "400g linguine",
          "500g shrimp, peeled and deveined",
          "4 cloves garlic, minced",
          "1/4 cup olive oil",
          "1/4 cup white wine",
          "2 tbsp butter",
          "1/4 cup parsley, chopped",
          "1 lemon",
          "Red pepper flakes",
          "Salt and pepper",
        ],
        instructions: [
          "Cook linguine according to package directions",
          "Heat olive oil in a large skillet over medium heat",
          "Add garlic and red pepper flakes, cook until fragrant",
          "Add shrimp and cook for 2-3 minutes per side",
          "Add white wine and simmer for 2 minutes",
          "Stir in butter and cooked pasta",
          "Garnish with parsley and lemon wedges",
        ],
        cooking_time: 25,
        difficulty: "Medium",
        servings: 4,
        image_url:
          "https://images.unsplash.com/photo-1563379091339-03246963d8a9?w=400",
      },
      {
        title: "Banana Bread",
        description: "Moist and delicious homemade banana bread",
        ingredients: [
          "3 ripe bananas",
          "1/3 cup melted butter",
          "1 cup sugar",
          "1 egg",
          "1 tsp vanilla extract",
          "1 tsp baking soda",
          "Pinch of salt",
          "1 1/2 cups all-purpose flour",
          "1/2 cup chopped walnuts (optional)",
        ],
        instructions: [
          "Preheat oven to 350°F (175°C) and grease a loaf pan",
          "Mash bananas in a large bowl",
          "Mix in melted butter, sugar, egg, and vanilla",
          "Add baking soda and salt, then fold in flour",
          "Stir in walnuts if using",
          "Pour into prepared pan and bake for 50-60 minutes",
          "Let cool in pan for 10 minutes before removing",
        ],
        cooking_time: 70,
        difficulty: "Easy",
        servings: 8,
        image_url:
          "https://images.unsplash.com/photo-1586444248902-2f64eddc13df?w=400",
      },
      {
        title: "Mushroom Risotto",
        description: "Creamy Italian risotto with wild mushrooms",
        ingredients: [
          "1 1/2 cups Arborio rice",
          "500g mixed mushrooms",
          "1 onion, diced",
          "3 cloves garlic, minced",
          "1/2 cup white wine",
          "4 cups vegetable broth",
          "1/2 cup Parmesan cheese",
          "2 tbsp butter",
          "2 tbsp olive oil",
          "Fresh thyme",
          "Salt and pepper",
        ],
        instructions: [
          "Heat broth in a saucepan and keep warm",
          "Sauté mushrooms in olive oil until golden, set aside",
          "Cook onion and garlic in butter until soft",
          "Add rice and stir for 2 minutes until translucent",
          "Add wine and stir until absorbed",
          "Add broth one ladle at a time, stirring constantly",
          "Stir in mushrooms, Parmesan, and thyme",
          "Season with salt and pepper and serve immediately",
        ],
        cooking_time: 45,
        difficulty: "Hard",
        servings: 4,
        image_url:
          "https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=400",
      },
      {
        title: "Smoothie Bowl",
        description: "Colorful and nutritious smoothie bowl with toppings",
        ingredients: [
          "2 frozen bananas",
          "1 cup frozen berries",
          "1/2 cup almond milk",
          "1 tbsp honey",
          "1/4 cup granola",
          "Fresh fruit for topping",
          "Chia seeds",
          "Coconut flakes",
          "Sliced almonds",
        ],
        instructions: [
          "Blend frozen bananas, berries, almond milk, and honey until smooth",
          "Pour into a chilled bowl",
          "Arrange granola, fresh fruit, and other toppings decoratively",
          "Sprinkle with chia seeds, coconut flakes, and almonds",
          "Serve immediately with a spoon",
        ],
        cooking_time: 15,
        difficulty: "Easy",
        servings: 1,
        image_url:
          "https://images.unsplash.com/photo-1511690743698-d9d85f2fbf38?w=400",
      },
      {
        title: "Fish Tacos",
        description: "Fresh and light fish tacos with cabbage slaw",
        ingredients: [
          "500g white fish fillets",
          "8 corn tortillas",
          "2 cups shredded cabbage",
          "1/4 cup mayonnaise",
          "1 lime",
          "1/2 cup flour",
          "1 tsp paprika",
          "1 tsp garlic powder",
          "Oil for frying",
          "Fresh cilantro",
          "Salsa verde",
        ],
        instructions: [
          "Mix flour with paprika and garlic powder",
          "Dredge fish in flour mixture and fry until golden",
          "Mix cabbage with mayonnaise and lime juice for slaw",
          "Warm tortillas in a dry skillet",
          "Break fish into pieces and place in tortillas",
          "Top with cabbage slaw, cilantro, and salsa verde",
          "Serve with lime wedges",
        ],
        cooking_time: 30,
        difficulty: "Medium",
        servings: 4,
        image_url:
          "https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=400",
      },
              {
          title: "Tiramisu",
          description: "Classic Italian dessert with coffee and mascarpone",
          ingredients: [
            "6 egg yolks",
            "1 cup sugar",
            "1 1/4 cups mascarpone cheese",
            "1 3/4 cups heavy cream",
            "2 packages ladyfinger cookies",
            "1 cup strong coffee, cooled",
            "2 tbsp coffee liqueur",
            "Cocoa powder for dusting",
            "Dark chocolate for garnish",
          ],
          instructions: [
            "Beat egg yolks and sugar until pale and thick",
            "Fold in mascarpone cheese",
            "Whip cream to stiff peaks and fold into mascarpone mixture",
            "Mix coffee with coffee liqueur",
            "Dip ladyfingers in coffee mixture and layer in dish",
            "Spread half the mascarpone mixture over cookies",
            "Repeat layers and refrigerate for 4 hours",
            "Dust with cocoa powder and garnish with chocolate",
          ],
          cooking_time: 60,
          difficulty: "Hard",
          servings: 8,
          image_url:
            "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400",
        },
        {
          title: "Pad Thai",
          description: "Authentic Thai stir-fried rice noodles with shrimp and peanuts",
          ingredients: [
            "200g rice noodles",
            "200g shrimp, peeled and deveined",
            "2 eggs",
            "1 cup bean sprouts",
            "1/2 cup chopped peanuts",
            "2 tbsp tamarind paste",
            "2 tbsp fish sauce",
            "1 tbsp palm sugar",
            "2 cloves garlic, minced",
            "2 tbsp vegetable oil",
            "Lime wedges",
            "Fresh cilantro",
          ],
          instructions: [
            "Soak rice noodles in warm water for 30 minutes",
            "Heat oil in a wok over high heat",
            "Add garlic and shrimp, stir fry until shrimp is pink",
            "Push ingredients aside and scramble eggs",
            "Add drained noodles and stir fry for 2 minutes",
            "Add tamarind paste, fish sauce, and palm sugar",
            "Add bean sprouts and stir fry for 1 minute",
            "Garnish with peanuts, cilantro, and lime wedges",
          ],
          cooking_time: 25,
          difficulty: "Medium",
          servings: 4,
          image_url:
            "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400",
        },
        {
          title: "French Onion Soup",
          description: "Classic French soup with caramelized onions and melted cheese",
          ingredients: [
            "4 large onions, thinly sliced",
            "4 tbsp butter",
            "2 tbsp olive oil",
            "1 tbsp sugar",
            "4 cups beef broth",
            "1 cup white wine",
            "4 slices French bread",
            "1 cup Gruyère cheese, grated",
            "2 cloves garlic",
            "Fresh thyme",
            "Salt and pepper",
          ],
          instructions: [
            "Melt butter and oil in a large pot over medium heat",
            "Add onions and cook for 30 minutes until caramelized",
            "Add sugar and continue cooking for 10 minutes",
            "Add wine and scrape bottom of pot",
            "Add broth and thyme, simmer for 30 minutes",
            "Toast bread and rub with garlic",
            "Ladle soup into bowls, top with bread and cheese",
            "Broil until cheese is melted and bubbly",
          ],
          cooking_time: 90,
          difficulty: "Medium",
          servings: 4,
          image_url:
            "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400",
        },
        {
          title: "Chocolate Mousse",
          description: "Light and airy chocolate mousse dessert",
          ingredients: [
            "200g dark chocolate",
            "4 large eggs, separated",
            "1/4 cup sugar",
            "1 cup heavy cream",
            "1 tsp vanilla extract",
            "Pinch of salt",
            "Fresh berries for garnish",
          ],
          instructions: [
            "Melt chocolate in a double boiler",
            "Whisk egg yolks and sugar until pale",
            "Fold melted chocolate into egg yolk mixture",
            "Whip cream to soft peaks",
            "Beat egg whites with salt until stiff peaks",
            "Gently fold whipped cream and egg whites into chocolate mixture",
            "Divide into serving glasses and refrigerate for 4 hours",
            "Garnish with fresh berries before serving",
          ],
          cooking_time: 30,
          difficulty: "Medium",
          servings: 6,
          image_url:
            "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=400",
        },
        {
          title: "Beef Bourguignon",
          description: "Classic French beef stew with red wine and mushrooms",
          ingredients: [
            "1kg beef chuck, cubed",
            "200g bacon, diced",
            "2 onions, diced",
            "3 carrots, sliced",
            "200g mushrooms, quartered",
            "2 cups red wine",
            "2 cups beef broth",
            "2 tbsp tomato paste",
            "3 cloves garlic, minced",
            "Fresh thyme and rosemary",
            "Salt and pepper",
          ],
          instructions: [
            "Brown beef in batches in a large Dutch oven",
            "Cook bacon until crispy, remove and set aside",
            "Sauté onions and carrots in bacon fat",
            "Add garlic and tomato paste, cook for 1 minute",
            "Return beef and bacon to pot",
            "Add wine, broth, and herbs",
            "Simmer covered for 2-3 hours until beef is tender",
            "Add mushrooms and cook for 15 minutes",
          ],
          cooking_time: 180,
          difficulty: "Hard",
          servings: 6,
          image_url:
            "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=400",
        },
        {
          title: "Greek Moussaka",
          description: "Layered eggplant casserole with ground lamb and béchamel sauce",
          ingredients: [
            "2 large eggplants, sliced",
            "500g ground lamb",
            "1 onion, diced",
            "3 cloves garlic, minced",
            "400g canned tomatoes",
            "1 tsp cinnamon",
            "1/2 tsp nutmeg",
            "4 tbsp butter",
            "4 tbsp flour",
            "2 cups milk",
            "2 egg yolks",
            "1/2 cup Parmesan cheese",
          ],
          instructions: [
            "Salt eggplant slices and let drain for 30 minutes",
            "Brown lamb with onion and garlic",
            "Add tomatoes and spices, simmer for 20 minutes",
            "Make béchamel sauce with butter, flour, and milk",
            "Layer eggplant, meat mixture, and béchamel",
            "Top with Parmesan cheese",
            "Bake at 375°F for 45 minutes until golden",
            "Let rest for 15 minutes before serving",
          ],
          cooking_time: 120,
          difficulty: "Hard",
          servings: 8,
          image_url:
            "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=400",
        },
        {
          title: "Apple Pie",
          description: "Classic American apple pie with flaky crust",
          ingredients: [
            "2 pie crusts",
            "6 cups apples, peeled and sliced",
            "3/4 cup sugar",
            "2 tbsp flour",
            "1 tsp cinnamon",
            "1/4 tsp nutmeg",
            "1 tbsp lemon juice",
            "2 tbsp butter",
            "1 egg, beaten",
            "1 tbsp sugar for sprinkling",
          ],
          instructions: [
            "Preheat oven to 425°F",
            "Mix apples with sugar, flour, spices, and lemon juice",
            "Line pie dish with bottom crust",
            "Fill with apple mixture and dot with butter",
            "Cover with top crust and crimp edges",
            "Cut slits in top crust and brush with beaten egg",
            "Sprinkle with sugar and bake for 45 minutes",
            "Cool on wire rack before serving",
          ],
          cooking_time: 75,
          difficulty: "Medium",
          servings: 8,
          image_url:
            "https://images.unsplash.com/photo-1586444248902-2f64eddc13df?w=400",
        },
        {
          title: "Ramen",
          description: "Japanese noodle soup with rich broth and toppings",
          ingredients: [
            "4 portions ramen noodles",
            "4 cups chicken broth",
            "2 tbsp soy sauce",
            "2 tbsp mirin",
            "4 soft-boiled eggs",
            "200g pork belly, sliced",
            "2 green onions, sliced",
            "1 cup bean sprouts",
            "Nori sheets",
            "Bamboo shoots",
          ],
          instructions: [
            "Simmer broth with soy sauce and mirin for 30 minutes",
            "Cook noodles according to package directions",
            "Cook pork belly until crispy",
            "Soft boil eggs for 6 minutes",
            "Assemble bowls with noodles, broth, and toppings",
            "Add sliced green onions, bean sprouts, and nori",
            "Top with soft-boiled egg and pork belly",
            "Serve immediately while hot",
          ],
          cooking_time: 45,
          difficulty: "Medium",
          servings: 4,
          image_url:
            "https://images.unsplash.com/photo-1563379091339-03246963d8a9?w=400",
        },
        {
          title: "Paella",
          description: "Spanish rice dish with seafood and saffron",
          ingredients: [
            "2 cups short-grain rice",
            "4 cups chicken broth",
            "1 pinch saffron",
            "200g shrimp",
            "200g mussels",
            "1 chicken breast, cubed",
            "1 onion, diced",
            "3 cloves garlic, minced",
            "1 red bell pepper, sliced",
            "1 cup frozen peas",
            "2 tbsp olive oil",
            "Lemon wedges",
          ],
          instructions: [
            "Heat oil in a large paella pan",
            "Sauté chicken until browned, remove and set aside",
            "Add onion, garlic, and bell pepper",
            "Add rice and stir for 2 minutes",
            "Add broth and saffron, bring to boil",
            "Add chicken and seafood",
            "Cook without stirring for 20 minutes",
            "Add peas and let rest for 5 minutes",
          ],
          cooking_time: 50,
          difficulty: "Hard",
          servings: 6,
          image_url:
            "https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=400",
        },
        {
          title: "Chicken Curry",
          description: "Spicy Indian curry with tender chicken and aromatic spices",
          ingredients: [
            "500g chicken breast, cubed",
            "2 onions, diced",
            "3 cloves garlic, minced",
            "1 inch ginger, grated",
            "2 tbsp curry powder",
            "1 tsp turmeric",
            "1 tsp cumin",
            "400ml coconut milk",
            "400g canned tomatoes",
            "Fresh cilantro",
            "Basmati rice",
          ],
          instructions: [
            "Heat oil in a large pan over medium heat",
            "Sauté onions until soft",
            "Add garlic, ginger, and spices",
            "Add chicken and cook until browned",
            "Add tomatoes and coconut milk",
            "Simmer for 20 minutes until chicken is cooked",
            "Garnish with fresh cilantro",
            "Serve with basmati rice",
          ],
          cooking_time: 40,
          difficulty: "Medium",
          servings: 4,
          image_url:
            "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400",
        },
        {
          title: "Pancakes",
          description: "Fluffy homemade pancakes with maple syrup",
          ingredients: [
            "2 cups all-purpose flour",
            "2 tbsp sugar",
            "2 tsp baking powder",
            "1/2 tsp salt",
            "2 large eggs",
            "1 3/4 cups milk",
            "1/4 cup melted butter",
            "1 tsp vanilla extract",
            "Maple syrup",
            "Fresh berries",
          ],
          instructions: [
            "Whisk together flour, sugar, baking powder, and salt",
            "In another bowl, whisk eggs, milk, butter, and vanilla",
            "Combine wet and dry ingredients until just mixed",
            "Heat griddle or pan over medium heat",
            "Pour 1/4 cup batter for each pancake",
            "Cook until bubbles form, then flip",
            "Cook until golden brown",
            "Serve with maple syrup and fresh berries",
          ],
          cooking_time: 20,
          difficulty: "Easy",
          servings: 4,
          image_url:
            "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400",
        },
        {
          title: "Sushi Roll",
          description: "Fresh California roll with avocado and crab",
          ingredients: [
            "2 cups sushi rice",
            "4 nori sheets",
            "1 avocado, sliced",
            "200g imitation crab meat",
            "1 cucumber, julienned",
            "2 tbsp rice vinegar",
            "1 tbsp sugar",
            "1 tsp salt",
            "Soy sauce",
            "Wasabi and pickled ginger",
          ],
          instructions: [
            "Cook sushi rice and season with vinegar mixture",
            "Place nori on bamboo mat",
            "Spread rice evenly on nori",
            "Add avocado, crab, and cucumber",
            "Roll tightly using bamboo mat",
            "Cut into 8 pieces with sharp knife",
            "Serve with soy sauce, wasabi, and ginger",
          ],
          cooking_time: 45,
          difficulty: "Hard",
          servings: 4,
          image_url:
            "https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=400",
        },
      ];

    for (const recipe of recipes) {
      await client.query(
        `
        INSERT INTO recipes (title, description, ingredients, instructions, cooking_time, difficulty, servings, image_url)
        VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
      `,
        [
          recipe.title,
          recipe.description,
          recipe.ingredients,
          recipe.instructions,
          recipe.cooking_time,
          recipe.difficulty,
          recipe.servings,
          recipe.image_url,
        ]
      );
    }

    console.log(`Seeded ${recipes.length} recipes successfully`);
  } finally {
    client.release();
  }
};

const main = async () => {
  try {
    await createTables();
    await seedData();
    console.log("Database setup complete!");
  } catch (error) {
    console.error("Error setting up database:", error);
  } finally {
    await pool.end();
  }
};

main();
